name: admin
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.2.0
  firebase_auth: ^5.1.2
  cloud_firestore: ^5.1.0
  firebase_storage: ^12.1.1
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.3
  provider: ^6.1.2
  flutter_iconly: ^1.0.2
  shimmer: ^3.0.0
  fancy_shimmer_image: ^2.0.3
  dynamic_height_grid_view: ^0.0.4
  card_swiper: ^3.0.1
  ionicons: ^0.2.2
  image_picker: ^1.1.2
  fluttertoast: ^8.2.6
  uuid: ^4.4.2
shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/images/
  - assets/images/categories/
  - assets/images/dashboard/

